Revert "reset"
SukhachevN/films-this-repo-is-outdated pull request #3
Opened 2021-09-12 15:49 UTC by SukhachevN

Reverts SukhachevN/films#2

2021-09-17 10:25 UTC, nrjshka requested changes
В целом: очень даже хорошо. Ты - красава! 👍🏻 
Посмотри комментарии. Я предложил, как можно улучшить эту версию.

2021-09-17 10:25 UTC, nrjshka commented on src/components/NavLink.js
> +  const className = classNames("NavLink", { NavLinkMatch: match });
Можешь прямо во `view` писать, это норм

2021-09-17 10:25 UTC, nrjshka commented on src/components/statusButtons.js
> +function Heart({ ...props }) {
можешь просто сделать:

```
function Heart(props) {
  return <BsFillHeartFill {...props} />
}
```

2021-09-17 10:25 UTC, nrjshka commented on src/components/statusButtons.js
> +function Clock({ ...props }) {
тут тоже

2021-09-17 10:25 UTC, nrjshka commented on src/components/statusButtons.js
> +function TV({ ...props }) {
тут тоже

2021-09-17 10:25 UTC, nrjshka commented on src/components/statusButtons.js
> +function Rate({ ...props }) {
тут тоже

2021-09-17 10:25 UTC, nrjshka commented on src/components/statusButtons.js
> +Heart = memo(Heart, comparator);
ты в memo можешь оборачивать in-place

так грязновато получается, что ты старую функцию перезаписываешь

2021-09-17 10:25 UTC, nrjshka commented on src/components/statusButtons.js
> +Rate = memo(Rate, comparator);
актуально для всех строк тут

2021-09-17 10:25 UTC, nrjshka commented on src/components/statusButtons.js
> +          ? dispatch(
это `view` или `container`?:)

2021-09-17 10:25 UTC, nrjshka commented on src/components/statusButtons.js
> +        info.id
Аналогично тут

2021-09-17 10:25 UTC, nrjshka commented on src/components/statusButtons.js
> +      {VideoKey ? (
1. для переменных мы используем snakeCase(нужно переименовать `VideoKey` в `videoKey` -- с большой буквы только компоненты)
2. ```
{videoKey && <a>...</a>}
```

2021-09-17 10:25 UTC, nrjshka commented on src/components/statusButtons.js
> +      className={`ProgressBar ${isFilmScreen ? "ProgressBarFilmScreen" : ""}`}
classnames

2021-09-17 10:25 UTC, nrjshka commented on src/components/statusButtons.js
> +Rating = memo(Rating, comparator);
аналогично тут

2021-09-17 10:25 UTC, nrjshka commented on src/redux/app/appMiddleWare.js
> +              emptyState,
в целом, все так
но функцию сложно читать, разбей ее на части

2021-09-17 10:25 UTC, nrjshka commented on src/redux/app/appMiddleWare.js
> +    const returnValue = next(action);
лучше так не делать, он у тебя заранее вызовет следующий экшен

вынесе вызов в конец, тут не нужно это делать

2021-09-17 10:25 UTC, nrjshka commented on src/redux/discover/discoverAcions.js
> +    return window
можно без `window`, просто обращайся к `fetch`. Если будешь код портировать под `nodeJs` там другой `global`.

2021-09-17 10:25 UTC, nrjshka commented on src/redux/discover/discoverAcions.js
> +      .then(async (response) => {
если тут используешь асинки, то перепиши весь код на асинки, либо так и продолжай использовать .then чейнинг

2021-09-17 10:25 UTC, nrjshka commented on src/redux/favourite/favouriteMiddleWare.js
> +    const returnValue = next(action);
тут тоже

2021-09-17 10:25 UTC, nrjshka commented on src/redux/favourite/favouriteMiddleWare.js
> +        window.localStorage.setItem("favourite", JSON.stringify(favourite));
имя стораджа в константу(используешь в двух местах)

2021-09-17 10:25 UTC, nrjshka commented on src/redux/favourite/favouriteMiddleWare.js
> +        window.localStorage.setItem("favourite", JSON.stringify(favourite));
"favourite"

2021-09-17 10:25 UTC, nrjshka commented on src/redux/filmInfo/filmInfoActions.js
> +};
я у тебя что-то подобное уже видел

можешь посмотреть: как можно сделать генератор для таких задач т.е. условный реквестор на минималках. 

по факту, должна быть функция, которая будет принимать диспатч, линку для запроса, функцию экшена для начала запроса, для успешного запроса и для провалившегося запроса. И она будет тебе возвращать какую-то функцию. 

Так ты сможешь сконцентрироваться только на логике

2021-09-17 10:25 UTC, nrjshka commented on src/redux/filmVideo/filmVideoActions.js
> +};
аналогично тут

2021-09-17 10:25 UTC, nrjshka commented on src/redux/watchLater/watchLaterMiddleWare.js
> +        window.localStorage.setItem("watchLater", JSON.stringify(watchLater));
константа для "watchLater"

2021-09-17 10:25 UTC, nrjshka commented on src/screens/App/AppContainer.js
> +  return <AppView handleSubmit={handleSubmit} data={data.discover} />;
код сложно читать
давай разбивать его пустыми строчками на логические блоки:
1. первые три строчки это монолитный блок(инициализация переменных)
2. потом у тебя должна быть пустая строчка перед `handleSubmit`
3. после `handleSubmit` тоже
4. каждый useEffect должен быть отделен пустой строчкой тк это самостоятельный логический блок
5. каждый return тоже

2021-09-17 10:25 UTC, nrjshka commented on src/screens/App/AppContainer.js
> +    dispatch(fetchDiscover("&sort_by=popularity.desc", GET_DISCOVER));
в константу

2021-09-17 10:25 UTC, nrjshka commented on src/screens/App/AppContainer.js
> +          `&query=${encodeURI(event.target.search.value)}`,
тут тоже

2021-09-17 10:25 UTC, nrjshka commented on src/screens/App/AppContainer.js
> +      dispatch(fetchDiscover("&sort_by=popularity.desc", GET_DISCOVER));
и тут

2021-09-17 10:25 UTC, nrjshka commented on src/screens/DiscoverScreen.js
> +        {!loading &&
вынеси в переменную

2021-09-17 10:25 UTC, nrjshka commented on src/screens/DiscoverScreen.js
> +        {!loading &&
сложное условие получается, сложно читать

2021-09-17 10:25 UTC, nrjshka commented on src/screens/FavouriteScreen.js
> +  const films = useSelector((state) => state.favourite.dataList);
хорошо, что ты используешь селекторы

можно лучше: выносить их все в папку с редаксом и шарить оттуда, чтобы ты каждый раз не повторял себя

2021-09-17 10:25 UTC, nrjshka commented on src/screens/Film.js
> +  );
тут тоже

2021-09-17 10:25 UTC, nrjshka commented on src/screens/Film.js
> +  const imagePath = "https://image.tmdb.org/t/p/w300/";
вынеси за пределы функции

2021-09-17 10:25 UTC, nrjshka commented on src/screens/FilmScreen/FilmScreenContainer.js
> +  if (data.filmInfo.error) {
пустая строка

2021-09-17 10:25 UTC, nrjshka commented on src/screens/FilmScreen/FilmScreenView.js
> +            {budget !== null && budget !== 0 ? `${budget} $` : "unknown"}
{Boolean(budge) && ..}

или 

{!!budge && ...}

2021-09-17 18:16 UTC, SukhachevN commented on src/components/NavLink.js
> +  const className = classNames("NavLink", { NavLinkMatch: match });
> Можешь прямо во `view` писать, это норм

Не понял что надо сделать.

2021-09-18 16:30 UTC, SukhachevN commented on src/redux/favourite/favouriteMiddleWare.js
> +    const returnValue = next(action);
Если я вынесу next(action) в конец, то у меня данные из `getState()` ещё не обновлены и в состоянии как до добавления фильма в люимые

2021-09-19 12:25 UTC, nrjshka approved these changes
LGTM 👍🏻 
Поправь на свое усмотрение

2021-09-19 12:25 UTC, nrjshka commented on src/redux/fetchFilmsRequest.js
> +      response.json().then((films) => dispatch(fetchSuccess(films)));
```
fetch(link)
 .then(response => resonse.json)
 .then(films =>...)
 .catch(...)
```

2021-09-19 12:25 UTC, nrjshka commented on src/screens/DiscoverScreen.js
> +    films.results.map((film) => <Film data={film} key={film.id} />);
Ты не совсем то вынес в константу

тебе нужно сделать что-то в стиле:
```
const isReady = !loading && films

return (
  {loading && ...}
  {isReady && ...}
)
```

2021-09-19 13:55 UTC, merged